### ISSUE TITLE
Missing games

### ISSUE THREAD

**Issue by nightblade9** [tauqua/gog-galaxy-itch.io#41]
I purchased the BLM bundle on Itch, which is ~1800 games. 

Itch integration adds ~1200 games to my library. I'm not sure where the other 600 are. (I'm using the numbers listed in GOG Galaxy under "Owned Games" as my metric.)

Is it possible the missing games are unknown ones? When I check owned games, I see several "unknown game" entries.

**Comment by nightblade9** [comment]
Update on this: I bought the Palestinian Aid bundle (1020 games), and my owned game count didn't increase.

Using my own fork of this code that lists unknown games, I get around 300 unknown games. That still leaves several hundred unaccounted for.

**Comment by tauqua** [comment]
This only lists Itch items which are categorized as "Game". There are other categories that items from the bundle fall into, including physical game, asset, soundtrack, etc. If you want to change this for your fork, it's in the arguments for the API call on line 75 of my current version. However, since Galaxy draws from IGDB which does not currently track physical games, etc. then almost none of these will be included. On the other hand, since the categorization is self-selected, you may get a few more from this.

**Comment by nightblade9** [comment]
Thanks for the explanation. I'm not sure why the number of games didn't increase that much with the new bundle, but the explanation makes sense.
