### ISSUE TITLE
Games From Bundles Not Displaying

### ISSUE THREAD

**Issue by tgiokdi** [tauqua/gog-galaxy-itch.io#64]
Just purchased my first extremely large bundle of about 1,000 games from Itch.io and was hoping to use GOG Galaxy to manage them all, but it appears that the bundle games do not get imported.  

Is that something that's already been investigated?

**Comment by tauqua** [comment]
Yes, this is a "feature" on Itch's end. 
`Note: Projects in this bundle are hidden in your library by default until you first access them in order to avoid flooding your library. You can return to this page at any time to access any projects you wish to show in your library.`
Games you purchase in a bundle are not added to your library until you click the "Download" button on the bundle page. At that point, they will be added to your library proper and show up through the plugin. 

If you want to activate them all in a batch, there are Greasemonkey scripts which help with that. Use the usual piece of caution when using Greasemonkey scripts.

Also, note that many of the items in these bundles are tabletop games, and are therefore intentionally not imported by the plugin. Some others will show up as "Unknown game" due to Galaxy behavior that a plugin is unable to address.
